/** Design philosophy: Field Notes Utility — a practical feature index uses native-like metadata artifacts rather than generic marketing cards. */

import { ArchiveRestore, ClipboardList, Copy, FileSearch, FolderTree, Hash, Link2, MapPinned, Search, Share2, ShoppingBag, Sparkles } from "lucide-react";
import SectionHeading from "@/components/SectionHeading";
import PhoneMockup from "@/components/PhoneMockup";
import { organizeAsset, referenceAsset, supportedPlatforms } from "@/lib/site";
import { usePageMeta } from "@/hooks/usePageMeta";

const features = [
  { icon: ClipboardList, title: "Offline Clipboard Manager", body: "Keep and reuse copied information with a focused local archive for the text and references you want to revisit.", artifact: ["Text · Local", "Saved item"] },
  { icon: Copy, title: "One-Tap Copy", body: "Copy a saved item back to your clipboard directly, without unnecessary duplication.", artifact: ["Action · Copy", "Reuse now"] },
  { icon: Sparkles, title: "Floating Bubble", body: "Access recent clips without leaving the app you are currently using.", artifact: ["Shortcut · Recent", "Cross-app"] },
  { icon: Hash, title: "Smart Hashtag Extractor", body: "Separate useful caption and hashtag information from supported content references.", artifact: ["#hashtag", "Caption reference"] },
  { icon: Link2, title: "Rich URL Preview", body: "Keep titles, descriptions, thumbnails, and available metadata with a saved public link.", artifact: ["URL · Public", "Preview metadata"] },
  { icon: MapPinned, title: "Google Maps Parser", body: "Collect useful location and business reference information from supported Google Maps URLs.", artifact: ["Location", "Business reference"] },
  { icon: ShoppingBag, title: "E-Commerce Product Extractor", body: "Organize available product information such as title, price, brand, image, ratings, and specifications.", artifact: ["Product detail", "Price · Brand"] },
  { icon: Share2, title: "Social Content Metadata", body: "Keep public metadata and reference information for supported public URLs, including available author information, captions, hashtags, thumbnails, or canonical links.", artifact: ["Public URL", "Caption · Author"] },
  { icon: FolderTree, title: "Folders & Organization", body: "Use Recent, Starred, Pinned, and custom folders to bring order to useful fragments.", artifact: ["Pinned", "Folder"] },
  { icon: ArchiveRestore, title: "Trash", body: "Recover removed local content before the 30-day cleanup cycle is complete.", artifact: ["Recovery", "30-day cleanup"] },
  { icon: Search, title: "Local Search", body: "Search through saved local content to quickly find something you already captured.", artifact: ["On-device", "Find again"] },
];

export default function Features() {
  usePageMeta({ title: "Features", description: "Explore Mr. Copy’s offline clipboard, link-reference, content organization, local search, and metadata features for Android.", path: "/features" });
  return <div className="features-page"><section className="page-hero"><div className="shell page-hero-ledger"><aside className="hero-ledger-rail" aria-hidden="true"><span>01</span><i /></aside><div className="page-hero-copy"><p className="eyebrow">Product features</p><h1>Useful information, kept usable.</h1><p>Mr. Copy helps turn copied text, public link metadata, hashtags, product details, and locations into references you can return to.</p></div></div></section><section className="section"><div className="shell"><SectionHeading index="02" eyebrow="The Mr. Copy toolkit" title="Capture context. Keep it organized." body="Every feature follows the same simple goal: reduce the distance between a useful fragment and the moment you need it again." /><div className="feature-catalog">{features.map((feature, index) => { const Icon = feature.icon; return <article className="catalog-card" key={feature.title}><div className="catalog-card-head"><span>{String(index + 1).padStart(2, "0")}</span><Icon size={19} aria-hidden="true" /></div><h2>{feature.title}</h2><p>{feature.body}</p><div className="catalog-artifact">{feature.artifact.map((item) => <span key={item}>{item}</span>)}</div></article>; })}</div></div></section><section className="section feature-image-section"><div className="shell visual-feature-grid"><img src={referenceAsset} alt="Mr. Copy reference detail mockup with preview data and a copy action" loading="lazy" /><div><p className="eyebrow">Public link references</p><h2>Context travels with the link.</h2><p>When a user saves a supported public URL, Mr. Copy may request that public target website or a metadata endpoint to retrieve information for the preview. That process is separate from locally saved clipboard content.</p><div className="feature-note"><FileSearch size={19} aria-hidden="true" /><span>Clipboard history is not uploaded to the cloud.</span></div></div></div></section><section className="section organization-band"><div className="shell visual-feature-grid reverse"><div><p className="eyebrow">Organize locally</p><h2>Build a dependable personal index.</h2><p>Use folders, starred and pinned items, trash recovery, and local search to bring practical order to the information you already captured.</p></div><img src={organizeAsset} alt="Mr. Copy organization cards for saved content and folders" loading="lazy" /></div></section><section className="section"><div className="shell support-section"><div><p className="eyebrow">Supported platforms</p><h2>Reference information from the places you use.</h2><p>Support depends on the public URL and the metadata available from the target website. Mr. Copy does not claim ownership of third-party content.</p></div><div className="platform-chip-board">{supportedPlatforms.map((platform) => <span key={platform}>{platform}</span>)}</div></div></section></div>;
}
