/** Design philosophy: Field Notes Utility — one factual plan is framed as a clear reference record, not an artificial pricing matrix. */

import { CircleHelp, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { p0Schemas } from "@/lib/seo";
import { usePageMeta } from "@/hooks/usePageMeta";

export default function Pricing() {
  usePageMeta({ title: "Mr. Copy Pricing and Availability", description: "Review Mr. Copy Android availability and Google Play billing information. Price, trial, and plan details are shown only when confirmed for release.", path: "/pricing", schema: p0Schemas.pricing });
  return <div className="pricing-page"><section className="page-hero pricing-hero"><div className="shell page-hero-ledger"><aside className="hero-ledger-rail" aria-hidden="true"><span>02</span><i /></aside><div className="page-hero-copy"><p className="eyebrow">Availability record</p><h1>Pricing details are being confirmed.</h1><p>Mr. Copy is planned for Android through Google Play. Public price, trial, and plan terms will appear here only after they are confirmed for release.</p></div></div></section><section id="availability" className="section pricing-section"><div className="shell pricing-layout"><aside className="pricing-aside"><span className="eyebrow">A clear boundary</span><h2>See the final offer before you commit.</h2><p>Mr. Copy does not offer web checkout. If a subscription becomes available, Google Play will manage the purchase flow and its current terms.</p><div className="pricing-note"><ShieldCheck size={19} aria-hidden="true" /><span>Google Play manages billing when an offer is published.</span></div></aside><article className="pricing-card"><div className="pricing-card-top"><span>Availability</span><small>Release details pending confirmation</small></div><div className="price"><strong>—</strong><span>Price and trial terms will be shown when confirmed.</span></div><div className="trial-badge">No public offer is published on this page yet.</div><div className="pricing-metadata"><span>Platform · Android</span><span>Billing · Google Play when available</span></div><p className="availability-status" role="status">The official Google Play link will appear here after release details are confirmed.</p><p className="pricing-fineprint">Deleting a Mr. Copy account does not automatically cancel a Google Play subscription. If you later subscribe, manage payment, renewal, and cancellation through Google Play.</p><p className="pricing-fineprint">Read <Link href="/privacy">what account data is used for identity and entitlement</Link>.</p></article></div></section><section className="section question-band"><div className="shell question-grid"><CircleHelp size={30} aria-hidden="true" /><div><h2>Need to manage a subscription?</h2><p>When a Mr. Copy subscription is available, use Google Play to view, change, or cancel it. Account deletion and Google Play subscription management are separate actions.</p></div></div></section></div>;
}
