/** Design philosophy: Field Notes Utility — one factual plan is framed as a clear reference record, not an artificial pricing matrix. */

import { Check, CircleHelp, ShieldCheck } from "lucide-react";
import { StoreCta } from "@/components/SiteShell";
import { siteConfig } from "@/lib/site";
import { usePageMeta } from "@/hooks/usePageMeta";

export default function Pricing() {
  usePageMeta({ title: "Pricing", description: "Mr. Copy Basic is available with a 3-day free trial and ₹49 per billing period through Google Play Billing, starting August 29, 2026.", path: "/pricing" });
  return <div className="pricing-page"><section className="page-hero pricing-hero"><div className="shell page-hero-ledger"><aside className="hero-ledger-rail" aria-hidden="true"><span>02</span><i /></aside><div className="page-hero-copy"><p className="eyebrow">Pricing record</p><h1>Simple pricing. Full access.</h1><p>One currently available plan for Mr. Copy on Android. No invented tiers, no web checkout.</p></div></div></section><section className="section pricing-section"><div className="shell pricing-layout"><aside className="pricing-aside"><span className="eyebrow">A clear start</span><h2>Try the workflow before you commit.</h2><p>Subscriptions are managed through Google Play. The official Google Play link will be added before launch.</p><div className="pricing-note"><ShieldCheck size={19} aria-hidden="true" /><span>Billing stays within Google Play.</span></div></aside><article className="pricing-card"><div className="pricing-card-top"><span>Basic</span><small>Available from {siteConfig.pricing.availableFrom}</small></div><div className="price"><strong>{siteConfig.pricing.amount}</strong><span>{siteConfig.pricing.period}</span></div><div className="trial-badge">{siteConfig.pricing.trial}</div><div className="pricing-metadata"><span>Plan · Basic</span><span>Billing · Google Play</span><span>Android</span></div><ul><li><Check size={17} aria-hidden="true" />Access to the current Mr. Copy functionality.</li><li><Check size={17} aria-hidden="true" />Subscriptions are managed through Google Play.</li><li><Check size={17} aria-hidden="true" />Product ID: {siteConfig.pricing.productId}</li></ul><StoreCta label="Start on Google Play" className="pricing-cta" /><p className="pricing-fineprint">Google Play Billing manages payment, renewal, and cancellation.</p></article></div></section><section className="section question-band"><div className="shell question-grid"><CircleHelp size={30} aria-hidden="true" /><div><h2>Need to manage a subscription?</h2><p>Use Google Play to view, change, or cancel your Mr. Copy subscription. Deleting a Mr. Copy account does not automatically cancel a Google Play subscription.</p></div></div></section></div>;
}
